### PR TITLE
Remove $NULL to directly return NULL

### PR DESCRIPTION
**Pull request by Lynesth**
Unless I missed something, this is not necessary so I removed it.

### CODE REVIEW

**Comment by gabordemooij** [comment]
PHP Stack trace:
PHP   1. {main}() /home/gabor/redbean/redbean/testje.php:0
PHP   2. RedBeanPHP\OODBBean->__get() /home/gabor/redbean/redbean/testje.php:22

Notice: Only variable references should be returned by reference in /home/gabor/redbean/redbean/rb.php on line 2529

Call Stack:
    0.0002     383304   1. {main}() /home/gabor/redbean/redbean/testje.php:0
    0.0063    2075840   2. RedBeanPHP\OODBBean->__get() /home/gabor/redbean/redbean/testje.php:22

/home/gabor/redbean/redbean/testje.php:22:
NULL

**Comment by gabordemooij** [comment]
https://github.com/gabordemooij/redbean/commit/0d0e3b945a183ea680e142f2b75f56a639ebd2b9

**Comment by Lynesth** [comment]
Yeah ok, I thought it was because of something like that.

I was thinking about a different approach for that function, I'll make a PR and you'll let me know what you think.

**Comment by gabordemooij** [comment]
I think I found a way to unit test this:
https://github.com/gabordemooij/redbean/commit/ae210e0621a663a03aefad592e4baa3b92dfd795

**Pull request closed without merging**
