### PR TITLE
Better adhere to Zend naming conventions and a bit of cleanup to make namespaces not conflict with classes

### PR DESCRIPTION
**Pull request by robertleeplummerjr**

### CODE REVIEW

**Comment by gabordemooij** [comment]
Sorry but I find these changes unnecessary and they might break backward compatibility with other peoples' projects. I don't see the need to conform to Zend Framework. Why do I care?

**Comment by robertleeplummerjr** [comment]
You stated: "RedBeanPHP is tied to Zend PHP, that's why it's called RedBeanPHP" from: https://github.com/gabordemooij/redbean/pull/434

Being tied to something else, yet not conforming to it seems like a bad idea.

**Comment by gabordemooij** [comment]
Zend PHP IS NOT Zend Framework
Zend PHP is the common term to refer to the original implementation of PHP by Zend (example: http://stackoverflow.com/questions/28192248/quick-switching-between-hhvm-and-zend-php).

I used the term Zend PHP to be specific, there are other versions as well: HHVM (slightly different implementation, some compatibility issues in PDO bindings), Hack (different syntax), RoadSend PHP (obsolete but still used).

**Comment by gabordemooij** [comment]
Zend Framework on the other hand is a very mediocre "Java'esque" framework by Weier O'Phinney that happens to bear the 'Zend' label.

**Comment by robertleeplummerjr** [comment]
Thanks for the clarification.

**Pull request closed without merging**
