### PR TITLE
Implemented R::findOneOrDispense

### PR DESCRIPTION
**Pull request by thiagocordeiro**
try to find a bean, if response is null, then dispense a brand new

### CODE REVIEW

**Comment by gabordemooij** [comment]
Hi,

Thanks for your pull request!

This function looks a lot like findOrDispense().
Why not simply wrap findOrDispense and add a reset()?

Also I miss a unit test for this new function, if you don't want to setup the entire unit test suite you can simply append a test to one of the existing packages and let Travis CI automatically test it for you.

cheers,
Gabor

**Comment by thiagocordeiro** [comment]
Hi Gabor, tks for this.

You are right, it looks like findOrDispense, the problem is findOrDispense
return an array.

Yes, I can use $bean = reset(R::findOrDispense()); but I think this seems
to be a little ugly

About test, sorry, belive, I'm not used to implement tests (yes, I have to
start doing this). So I'll try to do it for this

tks Gabor,

On Sat, Jun 11, 2016 at 8:23 AM, Gabor de Mooij <notifications@github.com>
wrote:

> Hi,
>
> Thanks for your pull request!
>
> This function looks a lot like findOrDispense().
> Why not simply wrap findOrDispense and add a reset()?
>
> Also I miss a unit test for this new function, if you don't want to setup
> the entire unit test suite you can simply append a test to one of the
> existing packages and let Travis CI automatically test it for you.
>
> cheers,
> Gabor
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gabordemooij/redbean/pull/504#issuecomment-225354163>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABBh8efV0VJ3YH8_FLAg63Rlnw-EOCfeks5qKpqtgaJpZM4IxgKD>
> .
>



-- 

Atenciosamente,

Thiago Cordeiro

(47) 9192-1602

**Comment by gabordemooij** [comment]
Okay, as soon as you have a test I'll merge this feature.
Feel free to ask any questions regarding unit tests, however I think with RedBeanPHP it's quite straight-forward, should take no more than a couple of lines of code.

**Comment by gabordemooij** [comment]
No unit tests.

**Pull request closed without merging**
