### PR TITLE
Add query methods to ToolBox

### PR DESCRIPTION
**Pull request by flip111**

### CODE REVIEW

**Comment by Lynesth** [comment]
I am not in favour of doing this as it's adding behavior to a toolbox which was just supposed to be a box.

To achieve what you are after, the whole Facade class should be rewritten to be instanciable instead. This is something that needs to be talked about though, but know that we are not against the idea. We need to come up with a way to keep everything backward compatible while giving users a way to work with multiple databases in an easier and more intuitive way. 

------

Meanwhile, I'll propose to you this simple class which you can use to achieve what you are looking for, if you want to. It should also be pretty update-proof since it only proxifies function calls.
_Please note that it hasn't been fully tested._
```php
class OOFacade {

    private $key;

    function __construct( $key, $dsn = NULL, $username = NULL, $password = NULL, $frozen = FALSE, $partialBeans = FALSE ) {
        R::addDatabase( $key, $dsn, $username, $password, $frozen, $partialBeans );
        $this->key = $key;
        return $this;
    }

    function __get( $property ) {
        R::selectDatabase( $this->key );
        return R::${$property};
    }

    function __call( $function, $args ) {
        R::selectDatabase( $this->key );
        return call_user_func_array( "R::{$function}", $args );
    }

}

// You can then use it like this:
$facade = new OOFacade( 'maindb', 'sqlite:/tmp/redbean.db' );
$facade->usePartialBeans( TRUE );

$user     = $facade->dispense('user');
$country  = $facade->dispense('country');
$language = $facade->dispense('language');
$user->name     = "Bob";
$country->name  = "Australia";
$language->name = "English";
$user->country  = $country;
$user->language = $language;

$facade->store($user);

// You can access public properties as well
$facade->toolbox;
$facade->toolboxes;
$facade->currentDB;

// You can then have one "facade" for each of your database connection
$backupDBFacade = new OOFacade( 'backupdb', 'sqlite:/tmp/redbean.db.bak' );
$backupDBFacade->usePartialBeans( TRUE );

$bob = $facade->findOne('user', ' ORDER BY id DESC ');

$backupDBFacade->store($bob);
```

**Comment by gabordemooij** [comment]
Toolbox is used for dependency injection, it was either that or just send an array of objects to every constructor. This PR does not make any sense to me.

**Comment by flip111** [comment]
> To achieve what you are after, the whole Facade class should be rewritten to be instanciable instead. This is something that needs to be talked about though, but know that we are not against the idea.

> Meanwhile

meanwhile of what? You both didn't say anything constructive of how to make Facade class instantiatable (or another way to adjust the PR) and just close this PR. Discussion is not going hold itself.

This is particularly annoying because of https://github.com/gabordemooij/redbean/issues/813#issuecomment-614659982

> Just send a PR to demonstrate what you have in mind.

> Maybe I should turn this into a general rule, might save some discussions. ;-)

wink wink

@gabordemooij if you don't understand the sense of a PR you can just ask "what is the sense of this PR?". You encourage doing PR, then "don't understand -> bam close". Cool.

**Comment by Lynesth** [comment]
> You both didn't say anything constructive of how to make Facade class instantiatable (or another way to adjust the PR) and just close this PR.

We understand what you are after, but this (adding logic to the Toolbox class) is not the way to do it and this is probably the reason it was closed. Because it makes no sense to add logic to the Toolbox class, not because your PR was not understood.

Making the whole facade class instanciable would be the most likely way to get it working. As I said though, this is something that needs to be talked about, especially how we could achieve that while keeping BC (or not).

**Meanwhile** (before we actually take the time to discuss that change and decide to make it or not), I provided you with a way to achieve what you wanted, Or did I miss something and it doesn't ?

**Comment by flip111** [comment]
> Or did I miss something and it doesn't work for you ?

I think you got it 100% Thank you for the code

**Pull request closed without merging**
