### PR TITLE
Fix new count() behavior in PHP 7.2

### PR DESCRIPTION
**Pull request by Lynesth**
This should fix https://github.com/gabordemooij/redbean/issues/611 the right way.
If I missed the reason for those checks in `findOrLike()` let me know.

### CODE REVIEW

**Comment by Lynesth** [comment]
Okay I found out why it didn't pass Travis. Will fix it.

**Comment by gabordemooij** [comment]
Unfortunately some tests did not pass...

**Comment by Lynesth** [comment]
Yeah, that's because of the part I removed in Finder.php which was actually used when queryRecord calls that glue sql stuff (ending up adding an "AND" in the query while it should not).

I need to dig deeper to propose something interesting and optimized. I'll try to find time next week ;)

Meanwhile, a thought related to this:
Are array of **conditions** only used with `findLike` and `findOrCreate` ? If so, was that a choice ? I mean, `findLike` is the same thing as `find` with just that that **conditions** parameter in right ?
Is there a wish/plan to add it to everything, like trash for example `R::trash("bean", [ "somecolumn" => [ "red", "blue" ] ])` ?

**Comment by gabordemooij** [comment]
R::trash takes a bean, not a string so I guess that is not really an option.

**Comment by gabordemooij** [comment]
I am all for uniformity but on the other hand I try to keep the code as compact as possible. If a feature is not really needed I try not to add it. Less code means less bugs. There cannot be a bug in code that does not exist.

**Comment by Lynesth** [comment]
Ok so this should be good now :)

During the making of those commits, I found out that a couple of tests are missing because those currently don't work while they should (fixed in this PR):

```php
$w = R::getWriter();
$w->queryRecordCount("bean", array( "somecolumn" => 1 ), " someothercolumn != '' ");
// This throws an SQL error because the glue adds a second "WHERE" before someothercolumn
// instead of a "AND"

$w->deleteRecord("bean", array( "somecolumn" => 1 ), " someothercolumn != '' ");
// Same error
```

So I decided to move the glueSQLCondition logic inside the makeSQLFromConditions function, so that everything is in the same place.

**Comment by gabordemooij** [comment]
Does the removal of

`$addSql = $this->glueSQLCondition`

in queryRecord and so on, not break backward compatibility?

**Comment by Lynesth** [comment]
Well, I'd say it shouldn't.

The glue is still here, just a bit lower. The difference is that if there's some $conditions then the glue is added inside the makeSQLFromConditions function instead.

So the only thing that changes work is the cache key, which now doesn't include the "WHERE" or "AND" in it. But it doesn't matter.

If you're thinking about something in particular just tell me what and I'll test it.

**Pull request merged**
