### PR TITLE
Add example of R::getPDO()->quote()

### PR DESCRIPTION
**Pull request by marios88**

### CODE REVIEW

**Comment by Lynesth** [comment]
I might have missed something here.
`R::exec` only returns affected rows so there's no point using it with a SELECT query.
You should use one of the `R::getX` functions instead (`R::getRow` in this case since we LIMIT 1).

Regarding preparation of the query, while I agree that escaping the table name is fine why not use what's already built in for the parameters ?

```php
$writer = R::getWriter();
$table = $writer->esc('unsafe_table_name');
$value = 'unsafe_string';
R::getRow("SELECT * FROM {$table} WHERE {$table}.title = ? LIMIT 1", [ $value ]);
```

**Comment by marios88** [comment]
my bad, R::exec was wrong for this example :)

> Regarding preparation of the query, while I agree that escaping the table name is fine why not use what's already built in for the parameters ?

In my case it was not possible to use bind params, but i get that this example might be out of scope for the manual

**Comment by Lynesth** [comment]
Why couldn't you use parameter binding ? That's interesting to know.

**Comment by marios88** [comment]
reworking legacy project, parts of the final query come from functions as strings ( ` AND field LIKE '%data%'` ), its not cost effective to rewrite using bindings

**Pull request merged**
