### PR TITLE
Break out create toolbox logic from addDatabase

### PR DESCRIPTION
**Pull request by flip111**
Because https://github.com/gabordemooij/redbean/pull/814 was merged and then reverted i can't change it without opening new PR.

### CODE REVIEW

**Comment by flip111** [comment]
Documentation change suggestion in https://github.com/gabordemooij/redbean/pull/814#issuecomment-614537023

**Comment by Lynesth** [comment]
Yep this passes all tests, can be merged.

**Comment by gabordemooij** [comment]
Let's try again!

**Comment by gabordemooij** [comment]
Okay, this merge went fine, thanks @flip111 !

**Pull request merged**
