### PR TITLE
Using Different table instead of tag or to maintain different types o…

### PR DESCRIPTION
**Pull request by lnt**
…f tags in project
Sometimes we dont use single type of tags in our project.
For example lets say I am maintaining Genre,Themes and keywords, basic nature of these three entities is Tag only. but still i need to maintain these separately.

I little bit changed the way from its basic convention of APIs.
Please check and let me know if its worth maintaining.
Thanks.

### CODE REVIEW

**Comment by lnt** [comment]
One can use 
` R::tagManager("keyword")->tag($page);
`
All apis remain same, except adding little config in start, not sure if follows basic guidelines.

**Comment by gabordemooij** [comment]
Thank you for the contribution I will take a look and let you know.

**Comment by gabordemooij** [comment]
oops acc. closed, reopened right away

**Comment by gabordemooij** [comment]
Sorry for the delay.
This feature looks fine, can you provide a unit test to demonstrate it works as intended (and so we can prevent regressions later on)?

**Comment by lnt** [comment]
No I had not written unit test yet, i was looking into unit test already
written, but cud not find where to put it, I will write it soon,

Best Regards
Lalit Tanwar

**Pull request closed without merging**
