### PR TITLE
SQLite foreign key suport - Issue #545

### PR DESCRIPTION
**Pull request by hausl**
See Issue #545

### CODE REVIEW

**Comment by hausl** [comment]
Travis ErrorLog says the driver is "mysql" (see Line 844). But the tested File is SQLiteT (see Line 871).

Might it be this is the reason for the error. Mysql of course does not support the PRAGMA statment, which i added in the **SQLite** QueryWriter(!).

```
842  Testpack: RedUNIT\Base\Database 
843	
844  ===== DRIVER : (mysql) =====
845
...
869  RedUNIT\Base\Database->testDriver [RedUNIT\Base\Database->testDriver] 
870  PHP Fatal error:  Uncaught [HY000] - Just a trouble maker
871  trace: #0 /home/travis/build/gabordemooij/redbean/testing/RedUNIT/Base/Database.php(392): RedUNIT\Base\TroubleDapter->get('PRAGMA foreign_...', Array)
```

**Comment by gabordemooij** [comment]
Well good news, I will have more time very soon and I will look into this :)

**Comment by gabordemooij** [comment]
See https://github.com/gabordemooij/redbean/issues/545

**Comment by gabordemooij** [comment]
Some tests have to be adjusted...

**Pull request closed without merging**
