### PR TITLE
Add message to PDOException on connect

### PR DESCRIPTION
**Pull request by ricardoboss**
I would be very helpful to know the reason why it could not connect to database. Adding the original exception message can help while debugging.

### CODE REVIEW

**Comment by Lynesth** [comment]
Hey there @ricardoboss 
PDO Exceptions were not bubbled on purpose.
See here for more information: https://redbeanphp.com/index.php?p=/connection

**Comment by ricardoboss** [comment]
Hi @Lynesth 
I eventually found the error which caused the exception, but I wasted half an hour because I didn't see the original exceptions message. I don't maintain this project, so I leave it up to you to decide if this PR makes sense/follows project guidelines.

**Comment by Rayraz** [comment]
Maybe it's a good idea to expose the original exception in debug mode only?

**Comment by gabordemooij** [comment]
> Maybe it's a good idea to expose the original exception in debug mode only?

We do not really have debug mode, only fluid mode, but that still does not mean it's safe to reveal the message.

> Hi @Lynesth
> I eventually found the error which caused the exception, but I wasted half an hour because I didn't see the original exceptions message. I don't maintain this project, so I leave it up to you to decide if this PR makes sense/follows project guidelines.

Better waste half an hour than have your server hacked.

**Comment by Rayraz** [comment]
> We do not really have debug mode, only fluid mode, but that still does not mean it's safe to reveal the message.

When I googled for a debug mode I ran into this flag: https://www.redbeanphp.com/index.php?p=/debugging
I haven't verified to see if it (still) works though. Is it obsolete?

I would agree that fluid mode isn't necessarily enough to jump to the conclusion that Redbean isn't running in a production environment. However, a flag that straight up prints queries including their payload to the screen is clearly something one should never use in production. IMHO, at that point you might as well just allow PDO Exceptions to be printed too.

**Comment by Lynesth** [comment]
Considering RedBean's policy, I think we'd need a new function to allow it, like `R::exposeOriginalPDOExceptions();`.
I don't really have a stance on this particular issue, I think rolling your own `new PDO( ... )` if you need to debug sounds fair enough to me.

**Pull request closed without merging**
