### PR TITLE
More info for troubleshooting PDO connection

### PR DESCRIPTION
**Pull request by alystair**
As per issue #361 - added detail about PDO connection errors, as well as try/catch PDO connection sample code.

### CODE REVIEW

**Comment by gabordemooij** [comment]
Please escape the dollar characters in the PHP code example, otherwise they will not appear.

**Comment by alystair** [comment]
Could use ' instead of " for code() function which ignores $ within the string... think of all the saved bits! I'll do it your way for now.

**Comment by gabordemooij** [comment]
Yeah but I like to use single quotes in the strings.

**Comment by gabordemooij** [comment]
Thanks anyway, manual updated

**Pull request merged**
