### PR TITLE
Added support for utf8mb4_unicode_520_ci

### PR DESCRIPTION
**Pull request by jreklund**
Hi,

I have added support for the collation utf8mb4_unicode_520_ci.
hasCap() logic borrowed from Wordpress.

Hopefully this will be of any use for you guys. I'm using it for database upgrades. (using freeze, so I'm doing it manually)

```php
// Select utf8mb4 or utf8 depending on MySQL/MariaDB
$charset_collate = $database->getDatabaseAdapter()->getDatabase()->getMysqlEncoding( TRUE );

// Search after the following inside .sql 
$search = array(
	'__DATABASE__',
	'__CHARACTER__',
	'__COLLATE__'
);

// Replace matching strings with
$replace = array(
	$settings["db"]["name"],
	$charset_collate['charset'],
	$charset_collate['collate']
);

str_replace($search,$replace,$sql);
```

### CODE REVIEW

**Comment by jreklund** [comment]
I can see that Travis failed on PHP 5.3 and that is indeed correct. PHP 5.3 don't have mysqlnd 5.0.9 and have no support for utf8mb4 as far as I can find. I have no idea how to skip that part of the test, to see if it fails somewhere else.
`#define MYSQLND_VERSION "mysqlnd 5.0.8-dev - 20102224 - $Id: 731e5b87ba42146a687c29995d2dfd8b4e40b325 $"`

**Comment by gabordemooij** [comment]
thanks for the contribution, unfortunately in order to pass it must work on 5.3 as well.

**Comment by jreklund** [comment]
According to all big PHP based software (Wordpress, Joomla, Drupal) support for utf8mb4 where not included in PHP 5.3 due to the fact it's utilizing mysqlnd 5.0.8 and all of them checks for mysqlnd 5.0.9 or greater.

So I need to rewrite testUTF8() to check for PHP < 5.4 and supply a utf8mb3 string instead of utf8mb4. Are that acceptable for you?

In all my local tests, PHP 5.3 works with utf8mb4 characters (han characters) but I have yet to find a official claim of why everyone checks for mysqlnd 5.0.9 or greater.

**Comment by r3wt** [comment]
@jreklund offtopic, but i'm curious what your use case is? UCA 5.2.0 is over 7 years old now, what do you hope to achieve by implementing it? just that its the latest sorting algorithm for unicode available in mysql or what? unicode_ci is based on 4.0.0, i'm not sure what the difference is. it only affects sort order for maybe a small handful of languages and characters. maybe it will matter for some languages but i'm not sure that's the case.

**Comment by jreklund** [comment]
@r3wt I have no use for it all all in my language (Swedish). I just upgraded a project from utf8mb3 into utf8mb4 and thought it where good to use the latest standard available. It's as you say; only affects sorting and not storing of characters.

**Pull request merged**
