### PR TITLE
Have trash/trashAll return number of deleted beans

### PR DESCRIPTION
**Pull request by Lynesth**
This is a proposal for #736 

```php
$book = R::load( 'book', 1 );
R::trash( $book ); // Returns 1

// ------

$books = R::findAll( 'book' );
count( $books ); // Returns 8
R::trashAll( $books ); // Returns 8

// ------

$book = R::dispense( 'book' );
R::store( $book );
$page = R::dispense( 'page' ); // We don't store it

// This will return 1 since $page doesn't get trashed
R::trashAll( [ $book, $page ] );

### CODE REVIEW

**Comment by Lynesth** [comment]
@benmajor Let me know if something like this would be good for you.

**Comment by gabordemooij** [comment]
Does this work with all supported databases?

**Comment by gabordemooij** [comment]
I tested this to be sure and it seems to work on MariaDB, MySQL, Postgres and SQLite. 

Turns out that the issue of portability is only with SELECT-statements:
https://www.php.net/manual/en/pdostatement.rowcount.php
https://stackoverflow.com/questions/34180011/sqlite-vs-mysql-rowcount

**Comment by gabordemooij** [comment]
Added a unit test for this.

**Comment by Lynesth** [comment]
Nice, thanks for finishing it.

**Pull request merged**
