### PR TITLE
Cleanup for use with .net

### PR DESCRIPTION
**Pull request by robertleeplummerjr**

### CODE REVIEW

**Comment by robertleeplummerjr** [comment]
Say hello to my little friend: https://github.com/robertleeplummerjr/redbean.net

**Comment by gabordemooij** [comment]
https://travis-ci.org/gabordemooij/redbean/jobs/57502593

why did you remove the &?

**Comment by robertleeplummerjr** [comment]
Ouch, my bad.  Phalanger wouldn't build with it, I believe it was because
the '&' in front of a method is for older php, like v4...  At least that is
what a quick google search told me:
http://stackoverflow.com/questions/1676897/what-does-it-mean-to-start-a-php-function-with-an-ampersand
What do you think?

On Tue, Apr 7, 2015 at 2:36 PM, Gabor de Mooij <notifications@github.com>
wrote:

> https://travis-ci.org/gabordemooij/redbean/jobs/57502593
>
> why did you remove the &?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gabordemooij/redbean/pull/434#issuecomment-90692955>.
>



-- 
Robert Plummer

**Comment by robertleeplummerjr** [comment]
Side note: So I'm getting ready to load up a simple example, but it keeps
imploding because the interfaces and namespaces conflict.  The .net
practice is to put an 'I' (upper case i) at the start of the type.  Would
you be open to this in your lib?

On Tue, Apr 7, 2015 at 3:20 PM, Robert Plummer <robertleeplummerjr@gmail.com
> wrote:

> Ouch, my bad.  Phalanger wouldn't build with it, I believe it was because
> the '&' in front of a method is for older php, like v4...  At least that is
> what a quick google search told me:
> http://stackoverflow.com/questions/1676897/what-does-it-mean-to-start-a-php-function-with-an-ampersand
> What do you think?
>
> On Tue, Apr 7, 2015 at 2:36 PM, Gabor de Mooij <notifications@github.com>
> wrote:
>
>> https://travis-ci.org/gabordemooij/redbean/jobs/57502593
>>
>> why did you remove the &?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/gabordemooij/redbean/pull/434#issuecomment-90692955>.
>>
>
>
>
> --
> Robert Plummer
>



-- 
Robert Plummer

**Comment by robertleeplummerjr** [comment]
I have unit tests now running on my system, and reproduced issue.  I'll
have it resolved shortly.

On Tue, Apr 7, 2015 at 3:23 PM, Robert Plummer <robertleeplummerjr@gmail.com
> wrote:

> Side note: So I'm getting ready to load up a simple example, but it keeps
> imploding because the interfaces and namespaces conflict.  The .net
> practice is to put an 'I' (upper case i) at the start of the type.  Would
> you be open to this in your lib?
>
> On Tue, Apr 7, 2015 at 3:20 PM, Robert Plummer <
> robertleeplummerjr@gmail.com> wrote:
>
>> Ouch, my bad.  Phalanger wouldn't build with it, I believe it was because
>> the '&' in front of a method is for older php, like v4...  At least that is
>> what a quick google search told me:
>> http://stackoverflow.com/questions/1676897/what-does-it-mean-to-start-a-php-function-with-an-ampersand
>> What do you think?
>>
>> On Tue, Apr 7, 2015 at 2:36 PM, Gabor de Mooij <notifications@github.com>
>> wrote:
>>
>>> https://travis-ci.org/gabordemooij/redbean/jobs/57502593
>>>
>>> why did you remove the &?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/gabordemooij/redbean/pull/434#issuecomment-90692955>
>>> .
>>>
>>
>>
>>
>> --
>> Robert Plummer
>>
>
>
>
> --
> Robert Plummer
>



-- 
Robert Plummer

**Comment by robertleeplummerjr** [comment]
I'm nearing 11k on unit test count for those completing.  I'm also cleaning
up a few documentation types and naming conventions so that it can actually
compile to .net.  I gotta hand it to you, you really built this thing well.

On Tue, Apr 7, 2015 at 5:44 PM, Robert Plummer <robertleeplummerjr@gmail.com
> wrote:

> I have unit tests now running on my system, and reproduced issue.  I'll
> have it resolved shortly.
>
> On Tue, Apr 7, 2015 at 3:23 PM, Robert Plummer <
> robertleeplummerjr@gmail.com> wrote:
>
>> Side note: So I'm getting ready to load up a simple example, but it keeps
>> imploding because the interfaces and namespaces conflict.  The .net
>> practice is to put an 'I' (upper case i) at the start of the type.  Would
>> you be open to this in your lib?
>>
>> On Tue, Apr 7, 2015 at 3:20 PM, Robert Plummer <
>> robertleeplummerjr@gmail.com> wrote:
>>
>>> Ouch, my bad.  Phalanger wouldn't build with it, I believe it was
>>> because the '&' in front of a method is for older php, like v4...  At least
>>> that is what a quick google search told me:
>>> http://stackoverflow.com/questions/1676897/what-does-it-mean-to-start-a-php-function-with-an-ampersand
>>> What do you think?
>>>
>>> On Tue, Apr 7, 2015 at 2:36 PM, Gabor de Mooij <notifications@github.com
>>> > wrote:
>>>
>>>> https://travis-ci.org/gabordemooij/redbean/jobs/57502593
>>>>
>>>> why did you remove the &?
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/gabordemooij/redbean/pull/434#issuecomment-90692955>
>>>> .
>>>>
>>>
>>>
>>>
>>> --
>>> Robert Plummer
>>>
>>
>>
>>
>> --
>> Robert Plummer
>>
>
>
>
> --
> Robert Plummer
>



-- 
Robert Plummer

**Comment by robertleeplummerjr** [comment]
I've opened an issue up with Phalanger team here: https://github.com/DEVSENSE/Phalanger/issues/51
and I've restored the '&'.  Also, I refactored so that I can build it and use it in .net.

**Comment by robertleeplummerjr** [comment]
Can I get some feedback on this?  I know it is somewhat a big commit, but I feel the impact of it being in both .net and php would be simply amazing.

**Comment by gabordemooij** [comment]
I appreciate your work and I think it's very valuable. However I will never ever allow any commit that makes changes to RedBeanPHP to make it work for another platform than Zend PHP.

RedBeanPHP is tied to Zend PHP, that's why it's called RedBeanPHP. I am willing to promote your work on twitter and provide a link on the website but I simply don't believe this will do justice to both projects. There is room for RedBeanNET, RedBeanPhalanager (or something like that) etc, even RedBeanRuby, but each of those projects should focus on their respective strengths. In my opinion incorporating these changes will damage both the Phalanger project and the PHP one.

**Comment by gabordemooij** [comment]
Also note that the & before the method is *not* an obsolete syntax. An & in front of a method means it will return a reference rather than a value. This is necessary to allow array-style access of beans. Removing the ampersand will return a value you can't modify anymore, even in the latest PHP versions. This is also why I believe we should keep the projects separate, this might very well be meaningless in a .NET/Phalanger environment.

In my opinion a language is something you don't change. A project cannot be 'portable' across multiple languages, because every language/platform has its own strengths (and weaknesses). Making projects portable means only focusing on the common weaknesses of those languages while never making use of specific strengths of a language/platform.

**Comment by robertleeplummerjr** [comment]
That is actually good news as I rolled back the '&'.  The other changes I
made were just standard php cleanup other than renaming interfaces to start
with an I for clarity.  Thank you clarifying the ampersand, as I've now
removed it and called phalanger out on it.  Were there be anything I could
do to make this commit acceptable?

**Comment by robertleeplummerjr** [comment]
I've got it!  After reading through Zend (which I'm very familiar with) the naming conventions you have acctaully don't line up with thiers.  To better make your library work with Zend I could rename them to end with "Interface" ( their requirement: http://framework.zend.com/manual/1.12/en/coding-standard.naming-conventions.html ) rather than be the same name as a namespace.  This could make your library more acceptable there and let it cross platform.  Win win!  So if I alter would you merge that?

**Pull request closed without merging**
