### PR TITLE
Saving some memory for echo.

### PR DESCRIPTION
**Pull request by dseguy**

### CODE REVIEW

**Comment by malukenho** [comment]
@dseguy I think it's a unnecessary optimisation. Do you can show how its affect the application, and if really save any considerable time?

**Comment by sohelrana820** [comment]
@dseguy I think this is not necessary.

**Comment by nuxwin** [comment]
Totally useless. Such optimization is like replacing double-quotes by single quote... Funny ;)

**Comment by gabordemooij** [comment]
Seems this guy is right: http://www.electrictoolbox.com/php-echo-commas-vs-concatenation/
Commas are faster. Not really important though for the debug function. However, it does not hurt. I never heard about this feature, but I like it. A comma is also a more 'natural' way to 'connect' various parts of a sentence. Nice work.

**Pull request merged**
