### PR TITLE
Update queryRecordWithCursor

### PR DESCRIPTION
**Pull request by Lynesth**
This PR adds the following features/modifications to queryRecordWithCursor (used to find collections):
- Adds flagNarrowFieldMode
- Allows the use of sqlFilters (because why not ?)
- And prevent it from breaking cache state (it's only a SELECT)

### CODE REVIEW

**Comment by Lynesth** [comment]
@gabordemooij I'll try to do it when I have some time, maybe end of week.

**Comment by gabordemooij** [comment]
Let's not forget about the unit tests though !

**Comment by Lynesth** [comment]
I've been really busy lately and apparently will be for the whole week, so I didn't get the time to write those tests.

Just to let you know I didn't forget :)

**Comment by gabordemooij** [comment]
No worries, I know how it works. Since I have my own company I am working 70hrs a week!

**Pull request merged**
